Early stop 변경
wafflestudio/snuboard-crawler pull request #207
Opened 2021-07-24 11:37 UTC by min112402

resolve #206 

Request queue에 추가된 공지사항이 모두 DB에 있는 경우 크롤러를 종료합니다.

2021-07-27 05:55 UTC, eldpswp99 requested changes
제가 생각한 것보다 많은 부분을 수정하지 않고도 구현이 가능하네요 좋습니다! 다만 고정된 공지사항 관련해서 문제가 있는듯 합니다. 컴공이나 정외같은 경우, 한 페이지에 고정된 공지사항이 모두 차지하는 경우가 있는데, 이 경우에 계속해서 첫 번째 페이지만 크롤링 하고 멈추게 됩니다. 이 부분 수정 부탁드리겠습니다. 정상적으로 동작하기 위해서는 고정되지 않은 페이지에서 early stop에 대한 감시가 이루어져야 할 것 같습니다

2021-07-27 11:02 UTC, min112402 commented
핀을 표시하는 방식을 고려하지 않았었네요. 수정했습니다.

핀되어있는 공지사항을 표시하는 방식은 세가지가 있습니다.
1. pin 되어있는 공지사항을 앞페이지에 몰아둔 경우 - cse, ir
2. pin 되어있는 공지사항이 모든 페이지에 등장하는 경우 - ere, cbe
3. pin 을 표시하지 않는 경우- ie 

pin되어있지 않은 공지사항이 하나도 없는 경우에는 early stop을 하지 않습니다.
이렇게 하면
-> cse 유형의 학과의 첫 n개 페이지에서 early stop하지 않습니다.
-> ere 유형의 학과에서도 가끔 모든 공지사항이 pin되어있는 공지사항과 중복될 수 있습니다. 이런때에도 cse와 마찬가지로 early stop하지 않습니다. 
-> 이외의 경우에는 게시판의 마지막페이지밖에 없으므로 early stop을 하지 않아도 크롤러의 handle list로직에 의해 종료됩니다.

2021-07-28 03:59 UTC, eldpswp99 requested changes
좋습니다 근데 제가 찾아보다가 category crawler에서 버그가 있어서 그거 고쳐서 같이 push해주시면 좋을 것 같습니다. 현재 카테고리크롤러에서 페이지를 주소에 숫자 있으면 그걸 page로 인식하고 나머지 잘라내는데, cbe의 college2 카테고리가 있어 다음 페이지로 가지 않는 문제가 있습니다 이 부분 확인 부탁드립니다!

2021-07-28 07:12 UTC, min112402 commented
> 좋습니다 근데 제가 찾아보다가 category crawler에서 버그가 있어서 그거 고쳐서 같이 push해주시면 좋을 것 같습니다. 현재 카테고리크롤러에서 페이지를 주소에 숫자 있으면 그걸 page로 인식하고 나머지 잘라내는데, cbe의 college2 카테고리가 있어 다음 페이지로 가지 않는 문제가 있습니다 이 부분 확인 부탁드립니다!

그렇군요.  확인해주셔서 감사합니다. 수정했습니다!

2021-07-28 08:47 UTC, eldpswp99 approved these changes
좋습니다

2021-07-28 08:56 UTC, merged